# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e35b385a5d461388098a99aec30056f1f6d4e3446893362bebfc8613c72698777499ce9d90437f65b340d4d67c9145767b9324919cfec589f9bed4fafe17da

test:
  secret_key_base: 5bda6fa6e39cb6f5b335e3c85463054044cc78eb174632cbfb1ceb8bd2fb275675eb4fe625f9a1b72b52ceb0651c123238ceabdf1ae55ad6c08ea599c4c7538b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
